-- VHDL automatically generated by the Electric VLSI Design System, version 
-- 9.07

-------------------- Cell 4_1_mux:mux{lay} --------------------
entity mux is port(A0, A1, A2, A3, S0, S1: in BIT; Y: out BIT; vdd: out BIT; 
    gnd: out BIT);
  end mux;

architecture mux_BODY of mux is
  component nMOStran port(poly_left, diff_top, diff_bottom: inout BIT);
    end component;
  component PMOStran port(poly_left, diff_top, diff_bottom: inout BIT);
    end component;
  component ground port(metal_1_well: inout BIT);
    end component;
  component power port(metal_1_substrate: inout BIT);
    end component;

  signal net_1, net_111, net_113, net_118, net_119, net_151, net_193, net_197, net_221
    , net_223, net_228, net_229, net_261, net_3, net_303, net_41, net_8, net_83,
     net_87, net_9: BIT;

begin
  nmos_0: nMOStran port map(S0, net_1, gnd);
  nmos_1: nMOStran port map(net_1, net_8, net_3);
  nmos_2: nMOStran port map(A0, gnd, net_8);
  nmos_3: nMOStran port map(S0, net_41, net_9);
  nmos_4: nMOStran port map(A2, gnd, net_41);
  nmos_5: nMOStran port map(net_9, net_83, net_87);
  nmos_6: nMOStran port map(net_3, gnd, net_83);
  nmos_7: nMOStran port map(S0, net_111, gnd);
  nmos_8: nMOStran port map(net_111, net_118, net_113);
  nmos_9: nMOStran port map(A1, gnd, net_118);
  nmos_10: nMOStran port map(S0, net_151, net_119);
  nmos_11: nMOStran port map(A3, gnd, net_151);
  nmos_12: nMOStran port map(net_119, net_193, net_197);
  nmos_13: nMOStran port map(net_113, gnd, net_193);
  nmos_14: nMOStran port map(S1, net_221, gnd);
  nmos_15: nMOStran port map(net_221, net_228, net_223);
  nmos_16: nMOStran port map(net_87, gnd, net_228);
  nmos_17: nMOStran port map(S1, net_261, net_229);
  nmos_18: nMOStran port map(net_197, gnd, net_261);
  nmos_19: nMOStran port map(net_229, net_303, Y);
  nmos_20: nMOStran port map(net_223, gnd, net_303);
  pmos_0: PMOStran port map(net_1, net_3, vdd);
  pmos_1: PMOStran port map(A0, vdd, net_3);
  pmos_2: PMOStran port map(S0, net_1, vdd);
  pmos_3: PMOStran port map(S0, net_9, vdd);
  pmos_4: PMOStran port map(A2, vdd, net_9);
  pmos_5: PMOStran port map(net_9, net_87, vdd);
  pmos_6: PMOStran port map(net_3, vdd, net_87);
  pmos_7: PMOStran port map(net_111, net_113, vdd);
  pmos_8: PMOStran port map(A1, vdd, net_113);
  pmos_9: PMOStran port map(S0, net_111, vdd);
  pmos_10: PMOStran port map(S0, net_119, vdd);
  pmos_11: PMOStran port map(A3, vdd, net_119);
  pmos_12: PMOStran port map(net_119, net_197, vdd);
  pmos_13: PMOStran port map(net_113, vdd, net_197);
  pmos_14: PMOStran port map(net_221, net_223, vdd);
  pmos_15: PMOStran port map(net_87, vdd, net_223);
  pmos_16: PMOStran port map(S1, net_221, vdd);
  pmos_17: PMOStran port map(S1, net_229, vdd);
  pmos_18: PMOStran port map(net_197, vdd, net_229);
  pmos_19: PMOStran port map(net_229, Y, vdd);
  pmos_20: PMOStran port map(net_223, vdd, Y);
  substr_5: ground port map(gnd);
  well_0: power port map(vdd);
end mux_BODY;
